# Generated by Django 5.0.6 on 2024-06-03 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.SmallIntegerField(
                choices=[(1, "Active"), (2, "Inactive")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="api.customer",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="api.customer",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.SmallIntegerField(
                choices=[(1, "completed"), (2, "rejected")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="paymentdetail",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_details",
                to="api.loan",
            ),
        ),
        migrations.AlterField(
            model_name="paymentdetail",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="api.payment",
            ),
        ),
    ]
